# Generated by Django 4.1.4 on 2023-01-16 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.ImageField(default='default-author-image.png', upload_to='author_images'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='default-book-cover.jpg', upload_to='book_covers'),
        ),
    ]
