# Generated by Django 4.1.4 on 2023-01-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_author_image_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='default-book-cover.png', upload_to='book_covers'),
        ),
    ]
