# Generated by Django 4.1.4 on 2023-01-25 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0006_userbookrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='readers',
            field=models.ManyToManyField(through='books.UserBookRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
