# Generated by Django 4.1.4 on 2023-02-03 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_bbk_book_copy_sign_book_pages_book_udp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='udp',
        ),
    ]
