# Generated by Django 4.1.4 on 2023-02-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_book_udp'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='inventory',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Инвентарный номер'),
        ),
    ]
