# Generated by Django 4.1.4 on 2023-02-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_remove_book_inventory_bookinstance_inventory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Русский', help_text='Enter a book language (e.g. English, Russian)', max_length=200, unique=True)),
            ],
        ),
    ]
