# Generated by Django 4.1.4 on 2023-02-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_author_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='Enter a book language (e.g. English, Russian)', max_length=200, unique=True),
        ),
    ]
