# Generated by Django 4.1.4 on 2023-02-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_remove_book_language_book_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='bbk',
        ),
        migrations.RemoveField(
            model_name='book',
            name='copy_sign',
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default='empty', help_text='Библиографическое описание', max_length=1500),
            preserve_default=False,
        ),
    ]
